spring:
  application:
    name: GATEWAY-SERVICE  
  cloud:
    gateway:
      routes:
        - id: visit-service
          uri: lb://VISIT-SERVICE
          predicates:
            - Path= /visit/**
        - id: medication-service
          uri: lb://MEDICATION-SERVICE
          predicates:
            - Path= /medication/**
          filters:
          - name: CircuitBreaker
            args:
              name: medication-service
              fallbackuri: forward:/medicationFallback  
         
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance: localhost
server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
